# Generated by Django 3.0.2 on 2020-01-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=0)),
                ('longt', models.FloatField(default=0)),
                ('alt', models.FloatField(default=0)),
                ('battery', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=15)),
                ('arm', models.CharField(max_length=10)),
            ],
        ),
    ]
